FROM mcr.microsoft.com/playwright:v1.36.1
 
WORKDIR /app

COPY package.json .
COPY tests/ ./tests/
COPY playwright.config.ts .
COPY tsconfig.json .

RUN npm i --legacy-peer-deps
ENV REUSE_SERVER=true

CMD ["npm", "run", "test"]
